### ISSUE TITLE
Side - Rotation binding

### ISSUE THREAD

**Issue by agrum** [pantherNZ/Ruhd-boardgame#1]
https://github.com/pantherNZ/Ruhd-boardgame/blob/64c7f541b8a94468d8f0fc871df11cc0cf8289fe/Ruhd/Assets/Scripts/TileComponent.cs#L15

I think you're limiting nice UX by forcing the rotation to only be multiples of 90. If you updated the visual rotation on tick you would get a better visual feedback of dragging effects.

`storedRotation` would need to be a `Side` rather than a `float` as well.

**Comment by pantherNZ** [comment]
Dammit, I mean I agree but I ended up spending 2 hours making nice rotation interpolations haha. Told myself I would polish later. Looks better though 👍
