### ISSUE TITLE
git ignore *.meta

### ISSUE THREAD

**Issue by agrum** [pantherNZ/Ruhd-boardgame#2]
https://github.com/pantherNZ/Ruhd-boardgame/blob/64c7f541b8a94468d8f0fc871df11cc0cf8289fe/Ruhd/Assets/Scripts/ScoresHandler.cs.meta#L1

I believe they are irrelevant to the repository, they'll be autogenerated and I don't think you'll customize them

**Comment by pantherNZ** [comment]
Not true actually, .meta files are very valuable as they store the asset's guid. I was saved by these once (and also wrecked) when I changed a script and then all the references to it were corrupted. But I could use the guid from the meta file to restore the references using a python script :)
